(* test_wots_verify.ml - WOTS+ verification engine test

   Tests the WOTS+ chain computation against reference vectors
   generated by reference_lms.py.
*)

open Hardcaml
open Hardcaml.Bits

let printf = Printf.printf

(* Convert hex string to Bits.t *)
let hex_to_bits ~width hex_str =
  of_hex ~signedness:Unsigned ~width hex_str

(* Convert Bits.t to hex string *)
let bits_to_hex b =
  let width = Bits.width b in
  let num_nibbles = (width + 3) / 4 in
  let s = Buffer.create num_nibbles in
  let i = ref (width - 1) in
  while !i >= 0 do
    let nibble_val = ref 0 in
    for bit_pos = 3 downto 0 do
      if !i >= 0 then begin
        if Bits.to_int (Bits.select b !i !i) = 1 then
          nibble_val := !nibble_val lor (1 lsl bit_pos);
        decr i
      end
    done;
    Buffer.add_char s (Printf.sprintf "%x" !nibble_val).[0]
  done;
  Buffer.contents s

(* Test vectors from reference_lms.py *)
let identifier_hex = "01010101010101010101010101010101"
let q = 5
let q_hash_hex = "aa065b6148ceeaa8c81db04e11fc7d3eec27543b3907531eec8d168a182cffdb"

let signature_hex = [|
  "0e2de492299e8156dfacbf1ec03bbcb52599ede943788bed3920d55728eb1e34";
  "82c3921882f45aa372c5a0a179026a37ab37c4d38eaf362c3bd00c66fd9334df";
  "adba34ba09cd0ccfa87b06db382ae56c01c33dda9353101b97ebed53cd72f34b";
  "ac7e002764095bde7aad441861a35c1b43160707c7c694c43cadd512ff2ee2e3";
  "717fa7feab85a0530ff203c357d7f4dfea8718aa1140ac4483bb0bd4b53aea38";
  "d7c241fd4ccc716ccaf74d875f412cf36abd0d8904ade866ad80f145ec5407d0";
  "b29c3dcc944f13f1b1f070c83924a0582896473d5844f5694c6a1cf5d6a866f0";
  "8ca6470cc80da05012cc7afd833a77c529824c9e3927264585b864259b3ece80";
  "cdbf66f9838c333acb89393b2b91071f12fd4ff440adc971e9100296201c9c5c";
  "65ba8116a0e1a92be8218d5706bb47487f4f2e3e03002e9f6d6f481542e1c9df";
  "da62bd591104856f9a2ec77bcf0aa8cf70c6dd2ab27412ac56717a45372bf441";
  "c05fab0cac40f5ce84d4666c392efe7199dd204f075a7ded2a7a0523960240bc";
  "f26762ea763c1733a1a30a7af78230182e38d8abbfa0e7d1337f66aee3eba688";
  "ad46cdfded589a821ec611c38544f3e2d3aa79e20c9caf06e46365d65d2b9d3a";
  "7c3307dcf2d58ed3de594d77cfafd07f955f8e935a60c04e27e272aa5a403721";
  "e8ea5539f2e2a97385fc67ee58e06452f5814927784fd9994882d5d88bd1ff6e";
  "4bb1d2e0943b956aacdcdca044bef49302a95760f094ebd55b9848149c129917";
  "2d9d6a92ffebbf39a75f9cb06ded43e6b457d0ddfa0f7fd19f68d8c2fc269bd1";
  "5248aca1d28ba43e8d2f06c609bffa700e1355860209b1b5fd9df89274f61548";
  "4b989de6a2f1375c356414a0390b429c87ac31e297354bfa550c7ca97b13d9e8";
  "1cf524de022aa1d3ccd6655797dd99e692e9471cc898765d3bdbd0394b6f827f";
  "5ecb607fdd644fe1e7054aee620ed3866d5d8c5246d93b3cc4321ac3bacc2b56";
  "999497c46e6a987771e44851fc89fdbc7c16c70535aec9d74d3d9f476cca50bc";
  "c448b625002da22f57385838a0af7ff19c9f1b2949552e08f9e7028f43e1b948";
  "13db9981798fd544385e44334390434bcd07885f527829557eefefc105f324d8";
  "6940fe1e194db390947835f5596529a9b950078f902d77408e979f2621333ec5";
  "5b3e28e058b54acaa76341672dbe9c823ba8194af396ab8d1cffd58f108c67e2";
  "f71544dd12ec9659b579871d341b0e48e4de10e4ed84d3c001f1e3e2021c1555";
  "96d08adc070a0c963057a63ac6b6550c5cff32470c25d945ba541ca9bb36f14b";
  "4ec09ccc34246687955f05cb00b899c97a81027e1168432a127061ce23c65461";
  "b6b414251cf1e68a90e59d6d69873cde55a8a27263a580522743f2658094920b";
  "34f7c494ecdf5bdb3b691d4e0bb7b1719b89b44c7305b18afb00f58a3c1777e6";
  "6716bdca8af8d614d4fb002009ebdbb988a893ce3bc92d168df119a99e467366";
  "5699094123021c7920326789738bb988fee851655a8f81572b239e77bddbe5cc";
|]

let digits = [|
  170; 6; 91; 97; 72; 206; 234; 168;
  200; 29; 176; 78; 17; 252; 125; 62;
  236; 39; 84; 59; 57; 7; 83; 30;
  236; 141; 22; 138; 24; 44; 255; 219;
  17; 151;
|]

let () =
  let scope = Scope.create ~flatten_design:true () in
  let module Sim = Cyclesim.With_interface(Wots_verify.I)(Wots_verify.O) in
  let sim = Sim.create (Wots_verify.create scope) in
  let inputs = Cyclesim.inputs sim in
  let outputs = Cyclesim.outputs ~clock_edge:Before sim in

  (* Reset *)
  inputs.clear := vdd;
  Cyclesim.cycle sim;
  inputs.clear := gnd;

  printf "=== WOTS+ Verification Test ===\n\n";

  (* Set up inputs *)
  inputs.message_hash := hex_to_bits ~width:256 q_hash_hex;
  inputs.expected_kc := hex_to_bits ~width:256 "414ae3da35b4957f89518ca59d6726fa416a7e5aaedcd337dec9c7debd86cf1e";
  inputs.identifier := hex_to_bits ~width:128 identifier_hex;
  inputs.leaf_index := of_int ~width:32 q;

  (* Start verification *)
  inputs.start := vdd;
  Cyclesim.cycle sim;
  inputs.start := gnd;

  (* Run the verification loop *)
  let max_cycles = 1_000_000 in
  let cycle_count = ref 0 in
  let chains_processed = ref 0 in

  while Bits.to_int !(outputs.done_) = 0 && !cycle_count < max_cycles do
    (* Check if WOTS is requesting a signature element *)
    if Bits.to_int !(outputs.request_sig_element) = 1 then begin
      let chain_idx = Bits.to_int !(outputs.chain_index) in
      if chain_idx < 34 then begin
        inputs.sig_element := hex_to_bits ~width:256 signature_hex.(chain_idx);
        inputs.sig_element_valid := vdd;
        Cyclesim.cycle sim;
        inputs.sig_element_valid := gnd;
        incr cycle_count;
        incr chains_processed;
        if !chains_processed <= 3 || !chains_processed = 34 then
          printf "  Chain %d: loaded (digit=%d, steps=%d)\n"
            chain_idx digits.(chain_idx) (255 - digits.(chain_idx));
      end else begin
        Cyclesim.cycle sim;
        incr cycle_count;
      end
    end else begin
      Cyclesim.cycle sim;
      incr cycle_count;
    end
  done;

  printf "\n  Total cycles: %d\n" !cycle_count;
  printf "  Chains processed: %d\n" !chains_processed;

  let valid = Bits.to_int !(outputs.valid) = 1 in
  let done_ = Bits.to_int !(outputs.done_) = 1 in
  printf "  Done: %b\n" done_;
  printf "  Valid: %b\n" valid;

  if done_ && valid then
    printf "\nWOTS+ verification test: PASS ✓\n"
  else
    printf "\nWOTS+ verification test: FAIL ✗\n"
