// Auto-generated by reference_lms.py — do not edit
// Merkle tree for HSS-LMS testbench

package tb_hss_tree_pkg;

    import arith_pkg::*;

    localparam int unsigned TREE_HEIGHT = 4;
    localparam int unsigned NUM_LEAVES  = 1 << TREE_HEIGHT;

    localparam int unsigned NUM_NODES   = 2*NUM_LEAVES - 1;

    localparam logic [127:0] IDENTIFIER =
        128'h01010101010101010101010101010101;

    localparam logic [WIDTH-1:0] MASTER_SEED =
        256'habababababababababababababababababababababababababababababababab;

    localparam logic [WIDTH-1:0] ROOT =
        256'h1c2e06bc6fe6bc3f7c6e7fc998277f82fd8fa2f79aa26eb1d3c66999083d4ce5;

    // Tree nodes: index 1 = root, 16..31 = leaves
    localparam logic [WIDTH-1:0] TREE [32] = '{
        // index 0 unused (default: '0)
         1: 256'h1c2e06bc6fe6bc3f7c6e7fc998277f82fd8fa2f79aa26eb1d3c66999083d4ce5,  // root
         2: 256'h73e75bf9cb843929ae85d8f6223c3f55dd1dc7b7292e2e338098cc69d6a4c4af,
         3: 256'hae749d878fe57433df878f2b4155c32cfec2358d46b64d8bca3759e5802a6a2d,
         4: 256'h04e412c0e49cf794208062b8917d60d21d4410f738792bf3f3e2472a0de192ba,
         5: 256'haa3942c12d1aa8d1675d23dbd6ae6634d6f7af4e725cc73836b683883816a69a,
         6: 256'h617eea0e55656b60169a2108fc66b132f172466a362cf8e0c068debe3c5ad45d,
         7: 256'h0de182c047aaa147e6429837cd1ceb6a5e8089f3c52a37710361d2345b5e66ea,
         8: 256'hc13ad4c0c09d17f80eb401f86faa93b3efe7b294f17cbe1e1a32418a8da6ec83,
         9: 256'ha425ef8e5e19a1946ce37a5a831a47047a3ad5f488c9c2ad60ed1a94486ed43a,
        10: 256'he8ef7feffbe70fca49ba2c79e6e18379a5f5c81089f6b39dd2311353eacc5f3e,
        11: 256'hbb2e3fd7fa4a51914aec2b24dafcdf68c292f2b019021f47cc2320dbf8174bb9,
        12: 256'h2347cd92d1134a77d51dda83498cdfa866776c6ce2c41ccbcbe6857f15f695f0,
        13: 256'h3da884699e783c69e9566fdd4f88fa779f5fe0c76fa1d1795fb11095a0bb2021,
        14: 256'h76e22c0038f50b81f50293d7ba94e193de0f96204a01568ae538c7ec8a9f723a,
        15: 256'h70dfacc996d6c634f701601c5d855215afccd89dc57498e0cf95284f9151fb08,
        16: 256'h053d1b7ae7324195deacbdbe0a1d5e583103f24613b6fcc52b8578105d6938d5,  // leaf 0
        17: 256'h40b13ec48ef2ad6471dc9e379fa3dce1e7f5f3b1ae9cc8072c9aa5552eef84f7,  // leaf 1
        18: 256'h3e03607b3cf02e320396a809db77e4261f9322d855998f4c996b929780325637,  // leaf 2
        19: 256'h5196a6b77629e930943cd6c58e81a4de59f1f496da971deb45e3a9ed3bb94c3b,  // leaf 3
        20: 256'h88e8870b6c5c462d0b438df1d9ec4fbf0da2dc0968b7908c943840d19342f63b,  // leaf 4
        21: 256'hfb8d108876e60082dc3329945d02017cd361903d3c384af6d7a55f34e2e47a36,  // leaf 5
        22: 256'hf84915c74d4c60df82087299c8659349d52d30ca3770c498a7a50adf7401653a,  // leaf 6
        23: 256'h80c91b26c969afbafc6fbf3c007100b133944aa30edc61cb2a5b80372d15f2a5,  // leaf 7
        24: 256'hf06cb620d5d4b9f9ef00b040a115d906cda0a1e542e61818bcc92a887b5fa52b,  // leaf 8
        25: 256'h5386d9a15e5d6821655f86bd16673158d74067928921341e080d8bd08ddc894e,  // leaf 9
        26: 256'h9fa7c2d9b45efad0035237eb2d2387b3fbb413762c53402dc2c002f21b398bdb,  // leaf 10
        27: 256'hd90fba6ef5dd496d6bc112a178d506da2a6280040b97611e7277237ab5bcdf93,  // leaf 11
        28: 256'h363d08a698ac8207f6fab75a53c69a4b9bc3d1fd6563f5324dfc3e56274d50a2,  // leaf 12
        29: 256'h74e4947bbea084e1d46154c43b1c37287a267b9b793751450d50fea2db50fe5c,  // leaf 13
        30: 256'h3d59cfcff7e6380caf07e177b9615d39e73f1894c814e73e93b59abb186f9ed0,  // leaf 14
        31: 256'h1ddf9e1b5c1aeff2e8d51e06cec1c9335cffc1bc3612111a4eeb7d91a316a8d5,  // leaf 15
        default: '0
    };

endpackage
