// Generated by gen_slh_vectors.py -- do not edit.
localparam int unsigned SLH_NUM_KEYS = 2;
localparam slh_key_t SLH_KEYS [SLH_NUM_KEYS] = '{
    '{seed: 128'h9e28978d02fa18bf8edc50912b94820b, root: 128'hb3170cb691200f4da7255edaac482a67},
    '{seed: 128'h269a0d804983087c48a885a3e02a0bf7, root: 128'hbd5e8c8a67c8966dccc92cfc6f05575b}
};
