name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Verilator
        uses: veryl-lang/setup-verilator@v1
        with:
          version: 5.044 # REVISIT: 5.046 used locally is not yet available on GitHub

      - name: Install Verible
        run: |
          VERIBLE_VERSION=v0.0-3946-g851d3ff4
          wget https://github.com/chipsalliance/verible/releases/download/${VERIBLE_VERSION}/verible-${VERIBLE_VERSION}-linux-static-x86_64.tar.gz
          tar xzf verible-${VERIBLE_VERSION}-linux-static-x86_64.tar.gz
          sudo cp verible-${VERIBLE_VERSION}/bin/* /usr/local/bin/

      - name: Lint Verilator ECDSA
        run: make lint TOOL=verilator CRYPTO_TYPE=0
        working-directory: verilog

      - name: Lint Verilator HSS-LMS
        run: make lint TOOL=verilator CRYPTO_TYPE=1
        working-directory: verilog

      - name: Lint Verible
        run: make lint TOOL=verible # verible does not compile the design, just checks syntax and style, no need to run separately for each CRYPTO_TYPE
        working-directory: verilog

  simulate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        tb: [top_ecdsa, top_hss]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Verilator
        uses: veryl-lang/setup-verilator@v1
        with:
          version: 5.044 # REVISIT: 5.046 used locally is not yet available on GitHub

      - name: Simulate ${{ matrix.tb }}
        run: make sim TB=${{ matrix.tb }}
        working-directory: verilog
